# Block is REQUIRED to get permission for the AccessToken
resources:
  repositories:
  - repository: AzureSyncRepo 
    type: git
    name: 'Gift of the Givers Foundation/GiftOfTheGiver_Foundation'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: __default
  jobs:
  - job: SyncRepo
    steps:
    
    # This forces the permission check
    - checkout: AzureSyncRepo
      path: 'azure-repo-dummy'

    # Manual script
    - task: CmdLine@2
      displayName: 'Sync GitHub to Azure Repos'
      inputs:
        script: |
          echo "Cloning GitHub repository..."
          # Since it's public, we don't need a token here
          git clone https://github.com/CodeByMathabo/GiftOfTheGiver_Foundation.git github-repo
          
          echo "Changing to GitHub repo directory..."
          cd github-repo
          
          echo "Configuring Git identity..."
          git config --global user.email "pipeline@azuredevops.com"
          git config --global user.name "Azure DevOps Pipeline"

          echo "Adding Azure Repo as a remote..."
          # This command uses the AccessToken we got permission for
          git remote add azure https://$(System.AccessToken)@dev.azure.com/ST10363312/Gift%20of%20the%20Givers%20Foundation/_git/GiftOfTheGiver_Foundation

          echo "Pushing code to Azure Repo..."
          git push -f azure HEAD:master