resources:
  repositories:
  - repository: AzureSyncRepo # alias
    type: git
    name: 'Gift of the Givers Foundation/GiftOfTheGiver_Foundation'

trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: __default
  jobs:
  - job: SyncRepo
    steps:
    
    # The repo to push FROM
    - checkout: self
      persistCredentials: true

    # This forces the pipeline to ask for permission for the Azure Repo
    # We check it out to a dummy path because we don't need its files.
    - checkout: AzureSyncRepo  # This MUST match the 'repository:' alias above
      path: 'azure-repo-dummy' # A temporary folder name

    # original script, now with a 'cd' command
    - task: CmdLine@2
      displayName: 'Sync GitHub to Azure Repos'
      inputs:
        script: |
          echo "Setting working directory..."
          # We must run the git commands inside the GitHub repo's folder
          cd $(Pipeline.Workspace)/s 

          echo "Configuring Git identity..."
          git config --global user.email "pipeline@azuredevops.com"
          git config --global user.name "Azure DevOps Pipeline"

          echo "Adding Azure Repo as a remote..."
          # This URL is the same and should now work
          git remote add azure https://$(System.AccessToken)@dev.azure.com/ST10363312/Gift%20of%20the%20Givers%20Foundation/_git/GiftOfTheGiver_Foundation

          echo "Pushing code to Azure Repo..."
          git push -f azure HEAD:master